apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ndyv16cdw-python
  janus-idp.io/tekton: ndyv16cdw-python
  backstage.io/kubernetes-id: ndyv16cdw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ndyv16cdw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
